version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pizzaria
    ports:
      - "3306:3306"
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge
